# Generated by Django 3.2.5 on 2021-07-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('fullname', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=70)),
                ('field', models.CharField(default='', max_length=70)),
                ('student_id_number', models.CharField(default='', max_length=70)),
                ('year_enrolled', models.CharField(default='', max_length=70)),
                ('age', models.CharField(default='', max_length=70)),
                ('marital_status', models.CharField(default='', max_length=70)),
                ('nationality', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
