# Generated by Django 3.2.5 on 2021-07-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
        ('students', '0003_student_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tutors',
            field=models.ManyToManyField(blank=True, to='tutors.Tutor'),
        ),
    ]
