# Generated by Django 3.2.5 on 2021-07-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_tutors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='tutors',
        ),
        migrations.RemoveField(
            model_name='student',
            name='field',
        ),
        migrations.AddField(
            model_name='student',
            name='field',
            field=models.ManyToManyField(blank=True, to='students.Field'),
        ),
    ]
