# Generated by Django 3.2.5 on 2021-07-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_tutors'),
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='students',
            field=models.ManyToManyField(blank=True, to='students.Student'),
        ),
    ]
