# Generated by Django 3.2.5 on 2021-07-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20210717_2035'),
        ('tutors', '0002_tutor_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='students',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='field',
        ),
        migrations.AddField(
            model_name='tutor',
            name='field',
            field=models.ManyToManyField(blank=True, to='students.Field'),
        ),
    ]
