# Generated by Django 3.2.5 on 2021-07-17 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20210717_2035'),
        ('tutors', '0003_auto_20210717_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='field',
        ),
        migrations.AddField(
            model_name='tutor',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='field', to='students.field'),
        ),
    ]
